services:
  sebadb:
    image: mariadb:11.1.2
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - db_data:/var/lib/mysql/

  wordpress:
    image: wordpress:php8.2-apache
    restart: always
    ports:
      - "${WORDPRESS_PORT:-8060}:80"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-0}
      WORDPRESS_AUTH_KEY: ${AUTH_KEY}
      WORDPRESS_SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
      WORDPRESS_LOGGED_IN_KEY: ${LOGGED_IN_KEY}
      WORDPRESS_NONCE_KEY: ${NONCE_KEY}
      WORDPRESS_AUTH_SALT: ${AUTH_SALT}
      WORDPRESS_SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
      WORDPRESS_LOGGED_IN_SALT: ${LOGGED_IN_SALT}
      WORDPRESS_NONCE_SALT: ${NONCE_SALT}
    volumes:
      - ./wordpress/web:/var/www/html
    depends_on:
      - sebadb

volumes:
  db_data: